version: '3.8'

services:
  frontend-prod:
    container_name: pimp-koto-frontend-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped