version: '3.8'

services:
  frontend-dev:
    container_name: pimp-koto-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - pimp-koto-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

volumes:
  pimp-koto-node-modules: